name: Deploy
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew bake
      - uses: actions/checkout@v2
                - name: copy
                env:
                  SRC_FOLDER_PATH: 'build/docs'
                  TARGET_BRANCH: 'gh-pages'
                run: |
                  files=$(find $SRC_FOLDER_PATH -type f) # get the file list
                  git config --global user.name 'GitHub Action'
                  git config --global user.email 'action@github.com'
                  git fetch                         # fetch branches
                  git checkout $TARGET_BRANCH       # checkout to your branch
                  git checkout ${GITHUB_REF##*/} -- $files # copy files from the source branch
                  git add -A
                  git diff-index --quiet HEAD ||  git commit -am "deploy files"  # commit to the repository (ignore if no modification)
                  git push origin $TARGET_BRANCH # push to remote branch
